<?php
// Import ACF Pro Custom fields groups
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_57757b161ed9e',
  'title' => 'אבטחה',
  'fields' => array (
    array (
      'key' => 'field_57757b258d0a9',
      'label' => 'הסתרת גרסת וורדפרס',
      'name' => 'hide_wp_version',
      'type' => 'select',
      'instructions' => 'האם תרצו להסתיר את גרסת הוורדפרס של האתר?
<br>
- אם אתם משתמשים בתוסף WordFence אין טעם להפעיל פונקציה זו כיוון שהיא מוגדרת כברירת מחדל.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'yes' => 'כן',
        'no' => 'לא',
      ),
      'default_value' => array (
        0 => 'yes',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 1,
      'ajax' => 1,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
    array (
      'key' => 'field_57757c9477bb5',
      'label' => 'ביטול עריכת קבצי תבניות/ תוספים דרך לוח הבקרה',
      'name' => 'disable_edit_in_control_panel',
      'type' => 'select',
      'instructions' => 'האם תרצו לבטל את האפשרות לערוך את קבצי התבניות והתוספים דרך לוח הבקרה? (נמצא תחת עיצוב>ערוך)
',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'yes' => 'כן',
        'no' => 'לא',
      ),
      'default_value' => array (
        0 => 'כן',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 1,
      'ajax' => 1,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
    array (
      'key' => 'field_5775839b72ebc',
      'label' => 'הסתרת שגיאת התחברות',
      'name' => 'hide_wp_login_errors',
      'type' => 'select',
      'instructions' => 'האם תרצו להסתיר את שגיאות ההתחברות ובמקום זאת להציג למשתמשים שגיאת התחברות אחידה?',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'yes' => 'כן',
        'no' => 'לא',
      ),
      'default_value' => array (
        0 => 'כן',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 1,
      'ajax' => 1,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
    array (
      'key' => 'field_577691f97dd67',
      'label' => 'נוסח שגיאת התחברות אחידה',
      'name' => 'single_login_error_message',
      'type' => 'text',
      'instructions' => 'במידה ובחרתם להפעיל את הפונקציה "הסתרת שגיאות התחברות" עליכם לנסח את שגיאת ההתחברות שתוצג למשתמשים שלא יצליחו להתחבר.',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_5775839b72ebc',
            'operator' => '==',
            'value' => 'yes',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'אופס! נראה שהפרטים שגויים.',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-theme-features',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_57758406323f4',
  'title' => 'ביצועים',
  'fields' => array (
    array (
      'key' => 'field_57758409497d1',
      'label' => 'טעינת קבצי JS בפוטר',
      'name' => 'load_js_in_footer',
      'type' => 'select',
      'instructions' => 'האם תרצו לטעון את קבצי ה-JS בפוטר במקום בהידר?',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'yes' => 'כן',
        'no' => 'לא',
      ),
      'default_value' => array (
        0 => 'כן',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 1,
      'ajax' => 1,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
    array (
      'key' => 'field_5775842c497d2',
      'label' => 'טעינת Jquery מ-Google CDN',
      'name' => 'load_jquery_google_cdn',
      'type' => 'select',
      'instructions' => 'האם תרצו לטעון את ה-Jquery דרך ה-CDN של גוגל?',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'yes' => 'כן',
        'no' => 'לא',
      ),
      'default_value' => array (
        0 => 'כן',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 1,
      'ajax' => 1,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
    array (
      'key' => 'field_57758462497d3',
      'label' => 'ביטול פיצ\'ר הסמיילים (Emoji)',
      'name' => 'disable_emoji',
      'type' => 'select',
      'instructions' => 'האם תרצו להסיר את הסמיילים באתר שלכם?
<br>
- אם אתם משתמשים בתוסף TinyMCE כדאי לא להפעיל פונקציה זו.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'yes' => 'כן',
        'no' => 'לא',
      ),
      'default_value' => array (
        0 => 'כן',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 1,
      'ajax' => 1,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
    array (
      'key' => 'field_57782faae5184',
      'label' => 'מחיקת Query Strings',
      'name' => 'remove_query_strings',
      'type' => 'select',
      'instructions' => 'האם תרצו להסיר Query strings מקבצים סטטיים?
',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'yes' => 'כן',
        'no' => 'לא',
      ),
      'default_value' => array (
        0 => 'לא',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 1,
      'ajax' => 1,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-theme-features',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_57768062bc422',
  'title' => 'נראות',
  'fields' => array (
    array (
      'key' => 'field_5776807c91312',
      'label' => 'שינוי טקסט הפוטר בלוח הבקרה',
      'name' => 'change_wp_admin_footer_text',
      'type' => 'text',
      'instructions' => 'האם תרצו לשנות את הטקסט בפוטר בלוח הבקרה?
<br>
ברירת המחדל היא: "WiPi Child Theme on Steroids"',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'default_value' => '<a href="https://www.davidrevivo.co.il/wipi-child-theme-%D7%AA%D7%91%D7%A0%D7%99%D7%AA-%D7%91%D7%AA/" alt="WiPi Child theme on steroids to download">WiPi Child Theme on Steroids</a>',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_5776811191313',
      'label' => 'לוגו מותאם אישית בטופס ההתחברות',
      'name' => 'change_wp_login_logo',
      'type' => 'image',
      'instructions' => 'על הלוגו להיות בגודל 80px*80px',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'full',
      'library' => 'all',
      'min_width' => 80,
      'min_height' => 80,
      'min_size' => '',
      'max_width' => 80,
      'max_height' => 80,
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_577681a091314',
      'label' => 'שינוי הurl של הלוגו בטופס ההתחברות',
      'name' => 'change_wp_login_logo_url',
      'type' => 'url',
      'instructions' => 'ברירת המחדל היא wordpress.org',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'http://www.wordpress.org/',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_577681f291315',
      'label' => 'שינוי כותרת הלוגו בטופס ההתחברות',
      'name' => 'change_wp_login_title',
      'type' => 'text',
      'instructions' => 'ברירת המחדל היא "פועל על וורדפרס"',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'פועל על וורדפרס',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-theme-features',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

endif;

?>
